// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSsn9A_txPOqHX17FZjoxf7TpvQIr3OYk',
    appId: '1:458461277010:web:b4434da4d4c6d13bffa88b',
    messagingSenderId: '458461277010',
    projectId: 'zara-f1a26',
    authDomain: 'zara-f1a26.firebaseapp.com',
    storageBucket: 'zara-f1a26.appspot.com',
    measurementId: 'G-NQT2109KDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGPArDVinR_OYOVl92UQ7f60igv5sBCxk',
    appId: '1:458461277010:android:0dc4506cd15eaf34ffa88b',
    messagingSenderId: '458461277010',
    projectId: 'zara-f1a26',
    storageBucket: 'zara-f1a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8pUzahv3P0N10dadNPMM5nKEzbOidQBU',
    appId: '1:458461277010:ios:f8c41cbc0178a00affa88b',
    messagingSenderId: '458461277010',
    projectId: 'zara-f1a26',
    storageBucket: 'zara-f1a26.appspot.com',
    iosBundleId: 'com.example.zaraclothingbrand',
  );
}
